version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install npm
          command: |
            npm install
            ls -l
      - run:
          name: Install AWS cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: AWS configure
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set default.region ${AWS_REGION}
      - run:
          name: Install aws dependencies
          command: |
            sudo apt-get install -y less && sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Showing files in folder
          command: ls -l
      - run:
          name: Install aws dependencies
          command: |
            sudo apt-get install -y less
      - run:
          name: Give scripts executable permission
          command: |
            cd scripts
            sudo chmod +x *.sh
            ls -al
            cd ..
            ls -l
      - run:
          name: Move files
          command: |
            mkdir ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}
            mv -t ./${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM} index.js scripts appspec.yml
            ls -l
            pwd
            cd ${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}
            pwd
            ls -l
            cd ..
      - run:
          name: Push to AWS S3
          command: >
            aws deploy push
            --application-name ${APPLICATION_NAME}
            --source ./${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}
            --s3-location s3://${S3BUCKET}/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}.zip
      - run:
          name: Create new revision deployment
          command: >
            aws deploy create-deployment
            --application-name ${APPLICATION_NAME}
            --deployment-group-name ${DEVELOPMENT_GROUP_NAME}
            --file-exists-behavior OVERWRITE
            --ignore-application-stop-failures
            --s3-location bucket=${S3BUCKET},key=${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}.zip,bundleType=zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
